
--
-- Target: Microsoft SQL Server 
-- Syntax: isql /Uuser /Ppassword /Sserver -i\path\filename.sql
-- Date  : Sep 27 2018 11:19
-- Script Generated by Database Design Studio 2.21.3 
--


--
-- Select Database: 'db_name'
--
USE db_name
GO

IF DB_NAME() = 'db_name'
    RAISERROR('''db_name'' DATABASE CONTEXT NOW IN USE.',1,1)
ELSE
    RAISERROR('ERROR IN BATCH FILE, ''USE db_name'' FAILED!  KILLING THE SPID NOW.',22,127) WITH LOG
GO

EXECUTE SP_DBOPTION 'db_name' ,'TRUNC. LOG ON CHKPT.' ,'TRUE'
GO

--
-- Permissions for: 'public'
--
GRANT ALL ON Teleselskab TO public
GO

GRANT ALL ON Town TO public
GO

GRANT ALL ON Adresse TO public
GO

GRANT ALL ON Person TO public
GO

GRANT ALL ON Note TO public
GO

GRANT ALL ON Email TO public
GO

GRANT ALL ON Telefonnummer TO public
GO

GRANT ALL ON AA TO public
GO
